# Generated by Django 4.0.2 on 2022-03-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imgae',
            new_name='image',
        ),
    ]
